databases:
  - name: TsunagaruPostDB
    databaseName: tsunagarupostdb
    user: ayayay
    region: singapore

services:
  - type: web
    name: TsunagaruPost
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase: 
          name: tsunagarupostdb
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false
